# values.yaml
replicaCount: 2

image:
  repository: "krivosoft/finbridge-test-task:latest"
  tag: "latest"
  pullPolicy: IfNotPresent

postgresql:
  image:
    repository: postgres
    tag: "13-alpine"
  auth:
    database: "app_db"
    user: "db_user"
    # Пароль пустой по ТЗ (передается через --set при установке)
    password: ""

ingress:
  enabled: true
  host: "app.local"