[cite_start]replicaCount: 2

image:
  repository: "krivosoft/finbridge-test-task"
  tag: "latest"
  pullPolicy: IfNotPresent

postgresql:
  image:
    repository: postgres
    tag: "13-alpine"
  auth:
    database: "app_db"
    user: "db_user"
    password: "" 

ingress:
  enabled: true
  [cite_start]host: "app.local"