apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "web-app-charts.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - [cite_start]host: app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "web-app-charts.fullname" . }}-app-svc
            port:
              number: 80