apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-app-charts.fullname" . }}-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-python
  template:
    metadata:
      labels:
        app: web-python
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - web-python
            topologyKey: "kubernetes.io/hostname"

      initContainers:
      - name: wait-for-db
        image: busybox:1.28
        command: ['sh', '-c', "until nc -zv {{ include 'web-app-charts.fullname' . }}-db-svc 5432; do echo waiting for db; sleep 2; done;"]

      containers:
      - name: python-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        envFrom:
        - secretRef:
            name: {{ include "web-app-charts.fullname" . }}-db-secret
        env:
        - name: DB_HOST
          value: {{ include "web-app-charts.fullname" . }}-db-svc
        - name: DB_NAME
          value: {{ .Values.postgresql.auth.database | quote }}
        - name: DB_USER
          value: {{ .Values.postgresql.auth.user | quote }}
        ports:
        - containerPort: 5000