apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web-app-charts.fullname" . }}-db-secret
type: Opaque
data:
  DB_PASSWORD: {{ required "Нужно передать пароль: --set postgresql.auth.password=secret" .Values.postgresql.auth.password | b64enc | quote }}